version: '2.2'
services:
  registry:
    image: registry:2.6.2
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry/simple.yml:/etc/docker/registry/config.yml
  ui:
    image: joxit/docker-registry-ui:static
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://registry:5000
      - URL=http://localhost:5000
    links:
      - registry:registry
    #volumes:
    #  - ./ui/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - registry
  apache:
    image: "httpd:2.4"
    hostname: myregistrydomain.com
    ports:
      - 5000:5000      
    links:
      - registry:registry
      - ui:ui
    volumes:
      - ./auth/httpd.groups:/usr/local/apache2/conf/httpd.groups
      - ./auth/httpd.htpasswd:/usr/local/apache2/conf/httpd.htpasswd
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
